/**
 * Shared type definitions for the Better Chatbot Worker.
 *
 * Provides interfaces used across modules: chat messages, model metadata,
 * provider groupings, and KV image records. Env is globally available via
 * `worker-configuration.d.ts` (generated by `wrangler types`) and does not
 * need to be imported.
 *
 * @module types
 */

/** A single message in a chat conversation. */
export interface ChatMessage {
  role: "user" | "assistant" | "system";
  content: string;
}

/** Metadata for a single AI model available in the model selector. */
export interface ModelInfo {
  id: string;
  name: string;
  provider: string;
  category: "chat" | "image" | "code" | "vision" | "embedding" | "audio" | "other";
  supportsStreaming: boolean;
}

/** A group of models from the same provider, displayed together in the UI dropdown. */
export interface ProviderGroup {
  provider: string;
  slug: string;
  models: ModelInfo[];
}

/** KV record for a Cloudflare Images upload — used by the cron cleanup job. */
export interface ImageRecord {
  imageId: string;
  url: string;
  createdAt: string;
}
